### ISSUE TITLE
Extension is not working in Safari Version 7, run on a MacBookPro using OS 10.9

### ISSUE THREAD

**Issue by tnievesnyc** [abbeycode/TumblrPlus#5]
When I click on the extension button nothing happens and the pull down menu is greyed out except for the HELP selection.

**Comment by abbeycode** [comment]
Thanks for the heads-up. I haven't upgraded to Mavericks yet, but will take a look as soon as I do.

**Comment by abbeycode** [comment]
@tnievesnyc can you attach a screenshot? I haven't been able to see this behavior myself in Mavericks (10.9).

**Comment by abbeycode** [comment]
I've verified that on Mac OS X 10.9.1 and Safari 7.0.1 it is working (Templates and Markdown utilities), but if someone can give me more information on how to reproduce this, we can reopen it.
